package com.artinus.membership.common.error;

public enum ArtinusErrorCode {
    INVALID__REQUEST_DATA,
    INVALID__SUBSCRIPTION_STATE,
    INVALID__SUBSCRIPTION_TYPE_FOR_SUBSCRIBE,

    NOT_FOUND__SUBSCRIPTION,
    NOT_FOUND__CHANNEL,
    NOT_FOUND__MEMBER,
    NOT_FOUND__PlAN_IN_CHANNEL,

    NOT_SUPPORTED_CHANNEL_TYPE,

    UN_SUBSCRIBE_CANT_HAVE_PLAN,

    EXTERNAL_REQUEST__ERROR,

    SERVER_ERROR
}
